export enum API_CALL_AUTHORIZATION {
    BASIC, JWT_BEARER_LOGIN, STOLEN_JWT_BEARER, OAUTH2
}

export enum CONFIGURATION_ERROR {
    NO_AUTH_TYPE, NO_CONFIGURATION, NO_CALCULATION_ENDPOINT, NO_USERNAME, NO_PASSWORD, NO_AUTH_ENDPOINT
}