version: "2.4"
services:

  nginx:
    build: ./projects/rpx
    container_name: reverseproxy
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - docker-service
    depends_on:
      - frontend
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  frontend:
    image: sebleich/storage-manager:latest
    container_name: storage-manager
    hostname: storage-manager
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - docker-service

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      WATCHTOWER_POLL_INTERVAL: 30
      WATCHTOWER_LABEL_ENABLE: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  docker-service:
    driver: bridge
    