version: "3.5"
services:

  certbot:
    image: certbot/certbot
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  frontend:
    image: sebleich/storage-manager:latest
    container_name: storage-manager
    hostname: storage-manager
    labels:
      com.centurylinklabs.watchtower.enable: true
    networks:
      - docker-service
    healthcheck:
      test: "exit 0"

  watchtower:
    image: containrrr/watchtower
    container_name: storage-manager-watchtower
    environment:
      WATCHTOWER_POLL_INTERVAL: 30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: nginx:latest
    container_name: reverseproxy
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - docker-service
    depends_on:
      frontend:
        condition: service_healthy
    volumes:
      - ./rpx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

networks:
  docker-service:
    driver: bridge
    