version: "2.4"
services:

  reverseproxy:
    build: ./projects/rpx
    container_name: storage-manager-reverseproxy
    ports:
      - "80"
      - "443"
    networks:
      - docker-service
    depends_on:
      - frontend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  frontend:
    image: sebleich/storage-manager:latest
    container_name: storage-manager
    hostname: storage-manager
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - docker-service

  watchtower:
    image: containrrr/watchtower
    environment:
      WATCHTOWER_POLL_INTERVAL: 30
      WATCHTOWER_LABEL_ENABLE: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  docker-service:
    driver: bridge
    