version: "2.4"
services:

  reverseproxy:
    build: ./projects/rpx
    container_name: storage-manager-reverseproxy
    ports:
      - "443:443"
    networks:
      - docker-service
    depends_on:
      - frontend

  frontend:
    image: sebleich/storage-manager
    container_name: storage-manager
    hostname: storage-manager
    networks:
      - docker-service

networks:
  docker-service:
    driver: bridge
    