export default {
    'DataObjectReference': 'bpmn:DataObjectReference',
    'DataInputAssociation': "bpmn:DataInputAssociation",
    'DataOutputAssociation': "bpmn:DataOutputAssociation",
    'EndEvent': 'bpmn:EndEvent',
    'ExclusiveGateway': 'bpmn:ExclusiveGateway',
    'Gateway': 'bpmn:Gateway',
    'Label': 'label',
    'ParallelGateway': 'bpmn:ParallelGateway',
    'SequenceFlow': 'bpmn:SequenceFlow',
    'ServiceTask': 'bpmn:ServiceTask',
    'StartEvent': 'bpmn:StartEvent',
    'Task': 'bpmn:Task',
    'TextAnnotation': 'bpmn:TextAnnotation',
}